import base64
import streamlit as st

def render_preview_card(parsed_data, image_file, desc_input):
    """將填寫的資料與圖片，渲染成適合手機截圖的精美 HTML 圖卡"""
    
    # 1. 取得需要顯示的資料 (安全防呆)
    def get_val(key, default="-"):
        val = parsed_data.get(key, {}).get('value', '')
        return val if val else default

    name = get_val("案名", "未命名物件")
    price = get_val("售價", "0")
    address = get_val("地址", "未提供地址")
    total_ping = get_val("登記總建坪", "0")
    main_ping = get_val("主建物坪數", "0")
    
    # 格局格式化 (例：3/2/2 -> 3房2廳2衛)
    layout = get_val("格局", "")
    layout_str = layout
    if layout and '/' in layout:
        parts = layout.split('/')
        labels = ['房', '廳', '衛', '陽台']
        layout_str = "".join([f"{p}{labels[i]}" for i, p in enumerate(parts) if i < len(labels)])
    elif not layout:
        layout_str = "-"

    floor = f"{get_val('位於樓層', '-')}F / {get_val('地上層', '-')}F"

    # 2. 處理圖片轉 Base64
    img_b64 = ""
    if image_file:
        try:
            img_bytes = image_file.getvalue()
            img_b64 = base64.b64encode(img_bytes).decode('utf-8')
            image_file.seek(0) # 指針歸零
        except:
            pass

    # 若有圖片，就產生圖片的 HTML 標籤 (不縮排)
    img_html = f'<div style="width: 100%; height: 200px; border-radius: 8px; overflow: hidden; margin-bottom: 15px; border: 1px solid #555;"><img src="data:image/jpeg;base64,{img_b64}" style="width: 100%; height: 100%; object-fit: cover;"></div>' if img_b64 else ""

    # 3. 組合 HTML 與 CSS (注意：這裡最左邊絕對不能有空白，否則會變程式碼區塊)
    html_content = f"""<div style="background: linear-gradient(135deg, #2c2c2c 0%, #1a1a1a 100%); padding: 20px; border-radius: 15px; border: 1px solid #D4AF37; box-shadow: 0 10px 20px rgba(0,0,0,0.8); color: white; font-family: 'Microsoft JhengHei', sans-serif; max-width: 400px; margin: 20px auto;">
<div style="border-bottom: 1px solid #444; padding-bottom: 10px; margin-bottom: 15px;">
<h2 style="margin: 0; color: #FFD700; font-size: 22px; font-weight: bold; line-height: 1.2;">{name}</h2>
<div style="color: #ccc; font-size: 13px; margin-top: 8px;">📍 {address}</div>
</div>
{img_html}
<div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px; background: rgba(255,215,0,0.1); padding: 10px 15px; border-radius: 8px; border: 1px dashed rgba(255,215,0,0.3);">
<span style="font-size: 16px; font-weight: bold; color:#ddd;">開價</span>
<span style="font-size: 26px; font-weight: bold; color: #ff4d4f; text-shadow: 1px 1px 5px rgba(255,77,79,0.3);">{price} <span style="font-size: 16px; color:#ddd;">萬</span></span>
</div>
<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 15px;">
<div style="background: rgba(255,255,255,0.05); padding: 10px; border-radius: 8px;">
<div style="color: #aaa; font-size: 12px; margin-bottom: 3px;">總建坪</div>
<div style="font-size: 16px; font-weight: bold; color: #FFD700;">{total_ping} 坪</div>
</div>
<div style="background: rgba(255,255,255,0.05); padding: 10px; border-radius: 8px;">
<div style="color: #aaa; font-size: 12px; margin-bottom: 3px;">主建物</div>
<div style="font-size: 16px; font-weight: bold;">{main_ping} 坪</div>
</div>
<div style="background: rgba(255,255,255,0.05); padding: 10px; border-radius: 8px;">
<div style="color: #aaa; font-size: 12px; margin-bottom: 3px;">格局</div>
<div style="font-size: 16px; font-weight: bold;">{layout_str}</div>
</div>
<div style="background: rgba(255,255,255,0.05); padding: 10px; border-radius: 8px;">
<div style="color: #aaa; font-size: 12px; margin-bottom: 3px;">樓層</div>
<div style="font-size: 16px; font-weight: bold;">{floor}</div>
</div>
</div>
<div style="background: rgba(255,255,255,0.05); padding: 15px; border-radius: 8px;">
<div style="color: #FFD700; font-weight: bold; font-size: 14px; margin-bottom: 8px;">✨ 物件特色：</div>
<div style="color: #ddd; font-size: 13px; line-height: 1.6; white-space: pre-wrap;">{desc_input if desc_input else "暫無提供特色描述"}</div>
</div>
<div style="text-align: center; margin-top: 15px; font-size: 10px; color: #666; letter-spacing: 1px;">
Generated by 物調整合studio
</div>
</div>"""
    
    # 渲染到畫面上
    st.markdown(html_content, unsafe_allow_html=True)
    st.success("📸 **圖卡生成成功！** 請直接將上方卡片「手機截圖」裁剪後，發送給客戶或 LINE 群組！")